"Ajouter/modifier/supprimer des données"
type Mutation {
    exampleHello(input: HelloInput!): Hello

    "Création d'une location"
    createRent(input: CreateRentInput): Rent

    "Arrêt d'une location"
    stopRent(input: StopRentInput): Rent
}
