# Le type query est un type spécial
# Chacune de ses propriétés va représenter un "point d'entrée" de notre API
# Du quel on pourra faire partir nos requêtes
"""
Récupérer les données
"""
type Query {

    "Liste des points de vente"
    getAllPointsOfSale(skip: Int, take: Int): [PointOfSale!]!

    "Liste des types de vélos"
    getAllKindsOfBike(skip: Int, take: Int): [KindOfBike!]!

    "Liste des vélos"
    getAllBikes(skip: Int, take: Int): [Bike!]!

}
