"Une location sélectionnée"
type Rent {
    id: Int!
    client_firstname: String
    client_lastname: String
    start_date: DateTime!
    back_date_planned: DateTime!
    back_date: DateTime
    bike: Bike!
    rent_point_of_sale: PointOfSale!
    return_point_of_sale: PointOfSale
}

"L'ajout d'une location"
input CreateRentInput {
    client_firstname: String!
    client_lastname: String!
    bike_id: Int!
    rent_point_of_sale_id: Int!
    back_date_planned: DateTime!
}

"L'arrêt d'une location"
input StopRentInput {
    rent_id: Int!
    bike_id: Int!
    return_point_of_sale_id: Int!
}